# Generated by Django 6.0 on 2025-12-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='hash_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
