# Generated by Django 6.0 on 2025-12-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_transacao_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
