# Generated by Django 5.2.9 on 2025-12-31 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_categoria_id_alter_conta_id_alter_transacao_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.conta'),
        ),
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('limite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_fechamento', models.IntegerField()),
                ('dia_vencimento', models.IntegerField()),
                ('bandeira', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('conta_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.cartaocredito'),
        ),
        migrations.CreateModel(
            name='FaturaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('data_fechamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paga', models.BooleanField(default=False)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cartaocredito')),
            ],
        ),
        migrations.AddField(
            model_name='transacao',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contas.faturacredito'),
        ),
    ]
