# Generated by Django 5.2.9 on 2026-01-03 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_conta_cartaocredito_transacao_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacredito',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transacao',
            name='fatura_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='contas.faturacredito'),
        ),
    ]
