# Generated by Django 5.2.9 on 2026-01-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_faturacredito_valor_pago_transacao_fatura_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturacredito',
            name='requer_atencao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faturacredito',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('PARCIAL', 'Parcialmente Paga'), ('CREDITO', 'Crédito/Excedente')], default='ABERTA', max_length=20),
        ),
    ]
