# Generated by Django 5.2.9 on 2026-01-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_faturacredito_requer_atencao_faturacredito_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturacredito',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PAGA', 'Paga'), ('PARCIAL', 'Parcialmente Paga'), ('CREDITO', 'Crédito/Excedente'), ('INCONSISTENTE', 'Inconsistente')], default='ABERTA', max_length=20),
        ),
    ]
