# Generated by Django 5.2.9 on 2026-06-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
